package handlers

import (
	"fmt"
	"net/http"

	"dokumentenscanner/internal/session"
	"dokumentenscanner/pkg/utils"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

// PDF handler configuration constants
const (
	// DefaultPDFFilename is the default filename for downloaded PDFs
	DefaultPDFFilename = "document.pdf"
)

// PDFHandler generates and returns a PDF for a session.
func PDFHandler(c *gin.Context) {
	deps := getDeps()
	sessionIDStr := c.Param("id")
	sessionID, err := uuid.Parse(sessionIDStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid session ID"})
		return
	}

	// Check if the session exists
	sess, exists := deps.SessionStore.Get(sessionID)
	if !exists {
		c.JSON(http.StatusNotFound, gin.H{"error": "session not found"})
		return
	}

	// Check if the session has uploaded images
	if len(sess.Images) == 0 {
		c.JSON(http.StatusBadRequest, gin.H{"error": "no images uploaded for this session"})
		return
	}

	// Check if PDF is ready (pre-generated by finalize)
	if len(sess.PDF) > 0 {
		// Return cached PDF
		c.Header("Content-Type", "application/pdf")
		c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", DefaultPDFFilename))
		c.Header("Content-Length", fmt.Sprintf("%d", len(sess.PDF)))
		c.Status(http.StatusOK)
		_, _ = c.Writer.Write(sess.PDF)
		return
	}

	// Fallback: generate PDF on the fly (backward compatibility)
	pdfBytes, err := utils.GeneratePDF(sess.Images[0])
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	// Store the PDF in the session
	sess.PDF = pdfBytes
	sess.Status = session.StatusReady
	deps.SessionStore.Update(sess)

	// Broadcast pdf_ready event to desktop clients
	message := fmt.Sprintf(`{"event":"pdf_ready","session_id":"%s"}`, sessionID)
	deps.WebSocketHub.Broadcast(sessionID, []byte(message))

	// Return the PDF
	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", DefaultPDFFilename))
	c.Header("Content-Length", fmt.Sprintf("%d", len(pdfBytes)))
	c.Status(http.StatusOK)
	_, _ = c.Writer.Write(pdfBytes)

	// Mark session as downloaded — cleanup goroutine will delete it
	sess.Status = session.StatusDownloaded
	sess.PDF = nil // Free memory
	deps.SessionStore.Update(sess)
}
